language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danno-mac/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danno-mac/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-370784509635"
  bucket_path: "docker-react"